PRO ..  yt_log

begin
    execute immediate 'drop table yt_log cascade constraints purge';
exception
    when others then
        null;
end;
/


create table yt_log (
    id                             number generated by default on null as identity 
                                   constraint yt_log_id_pk primary key,
    name                           varchar2(255 char)
                                   constraint yt_log_name_unq unique,
    created                        timestamp with local time zone not null,
    created_by                     varchar2(255 char) not null,
    updated                        timestamp with local time zone not null,
    updated_by                     varchar2(255 char) not null
)
;


