PRO ..  yt_stats

begin
    execute immediate 'drop table yt_stats cascade constraints purge';
exception
    when others then
        null;
end;
/

create table yt_stats (
    id                             number generated by default on null as identity 
                                   constraint yt_stats_id_pk primary key,
    log_id                         number
                                   constraint yt_stats_log_id_fk
                                   references yt_log on delete cascade,
    video_id                       varchar2(31 char)
                                   constraint yt_stats_video_id_fk
                                   references yt_video on delete cascade,
    view_count                     number,
    like_count                     number,
    comment_count                  number,
    created                        timestamp with local time zone not null,
    created_by                     varchar2(255 char) not null,
    updated                        timestamp with local time zone not null,
    updated_by                     varchar2(255 char) not null
)
;

-- table index
create index yt_stats_i1 on yt_stats (log_id);
create index yt_stats_i2 on yt_stats (video_id);